name: CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update:
    name: 更新
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: 依存関係のインストール
        run: pip install -r requirements.txt

      - name: ファイルを実行
        run: python bot.py
